"""
Graded module over the preprojective algebra Pi(Gamma), generated by one
vector at a framing vertex k, graded by path length.

This is the candidate model for the T-fixed-point representation of
DKK Prop 5.4 / Sec 5.4.2: V_i = ⊕_d V_i[d], maps raise degree by 1,
and "simple spectrum" means dim V_i[d] <= 1 for all i, d.

Doubled quiver: each edge {i,j} gives arrows both ways.
Preprojective relation at vertex i, applied to any x in V_i[d]:

        sum_{j ~ i}  eps(i,j) * M_{j->i} M_{i->j} (x)  =  0     in V_i[d+2]

with eps(i,j) = +1 if i->j is the chosen orientation of the edge, else -1.

We build the FREE graded module on walks from k and quotient by the
submodule generated by these relations (closed under left extension).
"""

from fractions import Fraction
from rootsys import RootSystem


# ------------------------------------------------------- linear algebra (Q)

def rref(rows, ncols):
    """Row-reduce a list of dict-sparse rows; return list of pivot rows."""
    mat = [dict(r) for r in rows if r]
    basis = []          # list of (pivot_col, row_dict)
    for r in mat:
        r = dict(r)
        for pc, br in basis:
            if pc in r and r[pc] != 0:
                f = r[pc] / br[pc]
                for c, val in br.items():
                    r[c] = r.get(c, Fraction(0)) - f * val
                    if r[c] == 0:
                        del r[c]
        r = {c: v for c, v in r.items() if v != 0}
        if r:
            pc = min(r)
            basis.append((pc, r))
    return basis


def rank(rows):
    return len(rref(rows, 0))


# ------------------------------------------------------------------ walks

def walks_from(rs, k, dmax):
    """walks[d] = list of walks (tuples of vertices) of length d starting at k."""
    walks = [[(k,)]]
    for d in range(dmax):
        nxt = []
        for p in walks[-1]:
            for j in sorted(rs.adj[p[-1]]):
                nxt.append(p + (j,))
        walks.append(nxt)
    return walks


def orientation(rs):
    """Fix an orientation: i->j whenever i<j."""
    return lambda i, j: 1 if i < j else -1


# ---------------------------------------------------------- graded module

def graded_module(rs, k, dmax=12):
    """Return dims[d][i] = dim V_i[d] for the Pi(Gamma)-module generated at k."""
    eps = orientation(rs)
    walks = walks_from(rs, k, dmax)
    index = [{p: n for n, p in enumerate(walks[d])} for d in range(dmax + 1)]

    # relation rows, by degree
    rels = {d: [] for d in range(dmax + 1)}
    for d in range(dmax - 1):
        for p in walks[d]:
            i = p[-1]
            row = {}
            for j in rs.adj[i]:
                q = p + (j, i)
                row[index[d + 2][q]] = row.get(index[d + 2][q], Fraction(0)) \
                    + Fraction(eps(i, j))
            if row:
                rels[d + 2].append(row)

    # close under left extension: if r = 0 in degree d, then r extended by
    # any further step is 0 in degree d+1.
    for d in range(dmax):
        for r in rels[d]:
            ext = {}
            for idx, val in r.items():
                p = walks[d][idx]
                for j in sorted(rs.adj[p[-1]]):
                    q = p + (j,)
                    ext.setdefault(j, {})
                    ext[j][index[d + 1][q]] = val
            for j, row in ext.items():
                rels[d + 1].append(row)

    # per-degree, per-vertex dimension of walks mod relations
    dims = []
    for d in range(dmax + 1):
        byvert = {}
        for i in rs.I:
            cols = [n for n, p in enumerate(walks[d]) if p[-1] == i]
            colset = set(cols)
            sub = []
            for r in rels[d]:
                rr = {c: v for c, v in r.items() if c in colset}
                if rr and len(rr) == len(r):     # relation lies inside V_i
                    sub.append(rr)
            byvert[i] = len(cols) - rank(sub)
        dims.append(byvert)
    return dims


def summarize(rs, k, dmax=10):
    dims = graded_module(rs, k, dmax)
    tot = {i: sum(dims[d][i] for d in range(len(dims))) for i in rs.I}
    return dims, tot


if __name__ == "__main__":
    print("Graded preprojective module generated at the framing vertex\n")

    cases = [
        ("Ex 5.4.4  D5 (1-2-3,3-4,3-5) framing at 3", "D", 5, 3, (1, 2, 3, 1, 1)),
        ("Ex 5.4.3  D4 framing at 2",                 "D", 4, 2, (1, 2, 1, 1)),
        ("Ex 5.10   D4 framing at 2",                 "D", 4, 2, (2, 2, 1, 1)),
        ("Ex 5.11   D5 framing at 2",                 "D", 5, 2, (1, 3, 2, 1, 1)),
        ("Ex 5.12   D5 framing at 2",                 "D", 5, 2, (2, 3, 2, 1, 1)),
    ]
    for label, typ, n, k, vexp in cases:
        rs = RootSystem(typ, n)
        dims, tot = summarize(rs, k, dmax=8)
        v = tuple(tot[i] for i in rs.I)
        print(label)
        for d in range(7):
            row = {i: dims[d][i] for i in rs.I if dims[d][i]}
            if row:
                print(f"    deg {d}: " + "  ".join(f"V{i}={c}" for i, c in row.items()))
        print(f"    total v = {v}   paper v = {vexp}   "
              f"{'MATCH' if v == vexp else 'DIFFERS'}")
        print()
