"""
Search graded submodules N of P = Pi e_k with dim(P/N) = v, and read off the
graded dimensions of the quotient.  Pi-modules are automatically I-graded
(the idempotents e_i lie in Pi), so N splits as a direct sum over vertices and
degrees -- the search is over subspaces of the small pieces P_d[i].
"""
from itertools import product
from rootsys import RootSystem, orbit_with_words
from wordtrace import trace, v_from_trace
from qvar import Proj, rref, P


def pieces(pr):
    """(d,i) -> list of column indices of P_d lying in vertex i."""
    out = {}
    for d in range(pr.dmax + 1):
        for n_, c in enumerate(pr.basis[d]):
            out.setdefault((d, c[-1]), []).append(n_)
    return out


def gen_submodule(pr, pc, d0, i0, coeffs):
    """Submodule generated by one homogeneous vector in P_{d0}[i0]."""
    N = {}
    vec = [0] * len(pr.basis[d0])
    for c, a in zip(pc[(d0, i0)], coeffs):
        vec[c] = a % P
    cur = {(d0, i0): [vec]}
    N[(d0, i0)] = [vec]
    for d in range(d0, pr.dmax):
        for (dd, ii), rows in list(cur.items()):
            if dd != d: continue
            for row in rows:
                for j in pr.rs.I:
                    img = pr.act(d, row, j)
                    if any(x % P for x in img):
                        key = (d + 1, j)
                        N.setdefault(key, []).append(img)
                        cur.setdefault(key, []).append(img)
    return {k: rref(v, len(pr.basis[k[0]]))[0] for k, v in N.items()}


def quot_dims(pr, pc, N):
    q = {}
    for (d, i), cols in pc.items():
        used = len(N.get((d, i), []))
        q[(d, i)] = len(cols) - used
    return q


def search(rs, k, v, dmax=8):
    pr = Proj(rs, k, dmax=dmax)
    pc = pieces(pr)
    target = dict(zip(rs.I, v))
    hits = []
    for (d0, i0), cols in sorted(pc.items()):
        n = len(cols)
        if n == 0: continue
        for coeffs in product(range(P), repeat=n):
            if all(a == 0 for a in coeffs): continue
            if next(a for a in coeffs if a) != 1: continue     # projective rep
            N = gen_submodule(pr, pc, d0, i0, coeffs)
            q = quot_dims(pr, pc, N)
            tot = {}
            for (d, i), c in q.items():
                tot[i] = tot.get(i, 0) + c
            if all(tot.get(i, 0) == target.get(i, 0) for i in rs.I):
                rows = {}
                for (d, i), c in q.items():
                    if c: rows.setdefault(d, {})[i] = c
                hits.append((d0, i0, coeffs, rows))
    return hits


if __name__ == "__main__":
    for label, (typ, n, k), word in [
        ("Ex 5.10", ("D", 4, 2), (1, 2, 3, 4, 2)),
        ("Ex 5.11", ("D", 5, 2), (2, 1, 3, 4, 5, 3, 2)),
        ("Ex 5.12", ("D", 5, 2), (2, 1, 2, 3, 4, 5, 3, 2)),
    ]:
        rs = RootSystem(typ, n)
        v = v_from_trace(rs, trace(rs, word, rs.fundamental(k)))
        hits = search(rs, k, v, dmax=8)
        print(f"{label}  v={v}:  {len(hits)} cyclic submodule(s) give the right dim vector")
        seen = set()
        for d0, i0, coeffs, rows in hits:
            sig = tuple(sorted((d, tuple(sorted(r.items()))) for d, r in rows.items()))
            if sig in seen: continue
            seen.add(sig)
            print(f"    generator in P_{d0}[{i0}]  -> quotient graded dims:")
            for d in sorted(rows): print(f"        deg {d}: {rows[d]}")
        print()
