"""
Direct computation of the quiver-variety point -- no heap assumptions.

For mu = w.lambda the variety M(v,w) is a single point, so the representation
is the unique stable one with dimension vector v.  It is generated by the
framing vector, hence a graded quotient of the projective  P = Pi e_k  (built
explicitly here with bases and matrices).  We therefore enumerate graded
submodules N of P and look for those with  dim(P/N) = v; the graded dimensions
of the quotient are the T-weights of the V_i, and SIMPLE SPECTRUM is the
statement that every graded piece has dimension <= 1.

Everything is done over F_p (p odd, structure constants are +-1).
"""
from itertools import product
from rootsys import RootSystem

import os
P = int(os.environ.get('DKKP', 7))

def inv(a): return pow(a, P - 2, P)

def rref(rows, n):
    rows = [r[:] for r in rows]
    piv = []
    r = 0
    for c in range(n):
        s = next((i for i in range(r, len(rows)) if rows[i][c] % P), None)
        if s is None: continue
        rows[r], rows[s] = rows[s], rows[r]
        f = inv(rows[r][c])
        rows[r] = [x * f % P for x in rows[r]]
        for i in range(len(rows)):
            if i != r and rows[i][c] % P:
                g = rows[i][c]
                rows[i] = [(rows[i][j] - g * rows[r][j]) % P for j in range(n)]
        piv.append(c); r += 1
        if r == len(rows): break
    return [row for row in rows[:r]], piv


class Proj:
    """P = Pi e_k, graded by path length, with explicit bases and arrow maps."""
    def __init__(self, rs, k, dmax=10):
        self.rs, self.k = rs, k
        eps = lambda i, j: 1 if i < j else -1
        walks = [[(k,)]]
        for _ in range(dmax):
            walks.append([p + (j,) for p in walks[-1] for j in sorted(rs.adj[p[-1]])])
        idx = [{p: n for n, p in enumerate(w)} for w in walks]
        # relations per degree (preprojective + left extensions)
        rel = {d: [] for d in range(dmax + 1)}
        for d in range(dmax - 1):
            for p in walks[d]:
                i = p[-1]
                row = [0] * len(walks[d + 2])
                for j in rs.adj[i]:
                    row[idx[d + 2][p + (j, i)]] = (row[idx[d + 2][p + (j, i)]] + eps(i, j)) % P
                rel[d + 2].append(row)
        for d in range(dmax):
            for r in rel[d]:
                ext = {}
                for c, val in enumerate(r):
                    if val % P == 0: continue
                    p = walks[d][c]
                    for j in sorted(rs.adj[p[-1]]):
                        ext.setdefault(j, [0] * len(walks[d + 1]))
                        ext[j][idx[d + 1][p + (j,)]] = val
                rel[d + 1].extend(ext.values())
        # basis of each graded piece: walks mod relations, split by end vertex
        self.basis = []       # basis[d] = list of walks forming a basis
        self.red = []         # reduction data per degree
        for d in range(dmax + 1):
            n = len(walks[d])
            R, piv = rref(rel[d], n)
            free = [c for c in range(n) if c not in piv]
            self.basis.append([walks[d][c] for c in free])
            self.red.append((R, piv, free, n))
        self.walks, self.idx, self.dmax = walks, idx, dmax

    def reduce(self, d, vec):
        R, piv, free, n = self.red[d]
        v = vec[:]
        for r, c in zip(R, piv):
            if v[c] % P:
                g = v[c]
                v = [(v[j] - g * r[j]) % P for j in range(n)]
        return [v[c] % P for c in free]

    def act(self, d, coeffs, j):
        """apply the arrow (into vertex j) to a degree-d element."""
        out = [0] * len(self.walks[d + 1])
        for c, val in zip(self.basis[d], coeffs):
            if val % P == 0: continue
            if j in self.rs.adj[c[-1]]:
                out[self.idx[d + 1][c + (j,)]] = (out[self.idx[d + 1][c + (j,)]] + val) % P
        return self.reduce(d + 1, out)

    def dims(self):
        out = []
        for d in range(self.dmax + 1):
            byv = {}
            for c in self.basis[d]:
                byv[c[-1]] = byv.get(c[-1], 0) + 1
            out.append(byv)
        return out


def submodule_from(pr, d0, vec):
    """graded submodule generated by a homogeneous vector; returns dict d->rows"""
    N = {d: [] for d in range(pr.dmax + 1)}
    N[d0] = [vec[:]]
    for d in range(d0, pr.dmax):
        R, piv = rref(N[d], len(pr.basis[d]))
        N[d] = R
        for row in R:
            for j in pr.rs.I:
                img = pr.act(d, row, j)
                if any(x % P for x in img):
                    N[d + 1].append(img)
    R, piv = rref(N[pr.dmax], len(pr.basis[pr.dmax]))
    N[pr.dmax] = R
    return N


def quotient_dims(pr, N):
    """graded dims of P/N, per (degree, vertex)."""
    out = []
    for d in range(pr.dmax + 1):
        # dimension of N restricted to each vertex is not well defined unless
        # N is spanned by vertex-homogeneous vectors; P_d already splits by
        # vertex, so project.
        cols = {}
        for n_, c in enumerate(pr.basis[d]):
            cols.setdefault(c[-1], []).append(n_)
        byv = {}
        for i, cs in cols.items():
            sub = []
            for row in N[d]:
                rr = [row[c] for c in cs]
                if any(x % P for x in rr) and all(row[c] % P == 0
                                                  for c in range(len(row)) if c not in cs):
                    sub.append(rr)
            R, _ = rref(sub, len(cs))
            byv[i] = len(cs) - len(R)
        out.append(byv)
    return out


if __name__ == "__main__":
    rs = RootSystem("D", 4)
    pr = Proj(rs, 2, dmax=6)
    print("P = Pi e_2 for D4, graded dims by (degree -> vertex:dim):")
    for d, byv in enumerate(pr.dims()):
        if byv: print(f"   deg {d}: {byv}")
    tot = {}
    for byv in pr.dims():
        for i, c in byv.items(): tot[i] = tot.get(i, 0) + c
    print("   total dim vector:", tuple(tot.get(i, 0) for i in rs.I))
