"""
Full sweep with the verified constructor.

Validity probes:
  (a) FALLBACK  -- the level sweep ran out of candidate levels and had to
      invent one (max+2).  The rule has broken down.
  (b) UNSTABLE  -- after moment-map edge repair, some element is no longer
      reachable upward from the minimum.  The representation is then not
      generated by the framing vector, so it is not a stable point: the
      colored-poset model fails, i.e. NOT simple spectrum.
"""
from rootsys import RootSystem, orbit_with_words
from wordtrace import trace
from heap2 import build_edges


def build_levels_flagged(rs, word, lam):
    L = {i: [] for i in rs.I}
    fallback = False
    pending = []

    def cands(i):
        nb = sorted({l for j in rs.adj[i] for l in L[j]})
        return [l + 1 for l in nb] if nb else [0]

    def place(i):
        nonlocal fallback
        for x in cands(i):
            if x not in L[i]:
                L[i].append(x); L[i].sort(); return
        fallback = True
        L[i].append((max(L[i]) + 2) if L[i] else 0); L[i].sort()

    for _, i, c, _ in trace(rs, word, lam):
        place(i)
        pending += [i] * (c - 1)
    for i in pending:
        nb = [l for j in rs.adj[i] for l in L[j]]
        x = (max(nb) + 1) if nb else 0
        while x in L[i]:
            x += 1; fallback = True
        L[i].append(x); L[i].sort()
    return {i: ls for i, ls in L.items() if ls}, fallback


def connected(elts, E):
    base = min(elts, key=lambda e: e[1])
    seen = {base}
    changed = True
    while changed:
        changed = False
        for (a, b) in E:
            if a in seen and b not in seen:
                seen.add(b); changed = True
            if b in seen and a not in seen:
                seen.add(a); changed = True
    return len(seen) == len(elts)


for typ, n, k in [("D",4,2),("D",5,2),("D",6,2),("D",6,3),("D",7,3),("E",6,2),("A",5,3),("D",5,1)]:
    rs = RootSystem(typ, n); lam = rs.fundamental(k)
    orb = orbit_with_words(rs, lam)
    tot = fb = unst = 0
    bad_examples = []
    for mu, word in sorted(orb.items(), key=lambda t: len(t[1])):
        if not word: continue
        tot += 1
        L, fallback = build_levels_flagged(rs, word, lam)
        elts, E = build_edges(rs, L)
        conn = connected(elts, E)
        if fallback: fb += 1
        if not conn:
            unst += 1
            if len(bad_examples) < 3:
                bad_examples.append((word, L))
    print(f"{rs.name()} om{k}: |orbit|={tot:4d}  fallback={fb:3d}  disconnected={unst:3d}")
    for word, L in bad_examples:
        print(f"     e.g. w={''.join('s'+str(i) for i in word)}  levels={dict(sorted(L.items()))}")
