"""
Explicit representations of products of type-A factors, so that the direct
Theorem 1.2 test of nullcone.py / mq.py works beyond SL2^k.

This matters because the SL2^k search came up empty: there, Hesselink-type
coincides exactly with the trivial-type extended quivers, which is precisely
the class Krylov-Wang can already prove.  So a counterexample to Conjecture
1.6 has to live at some other semisimple group, and those are the ones we
could not previously test.

Construction.  For a single factor of type A_n the standard representation is
C^{n+1} with Chevalley generators e_i = E_{i-1,i}, f_i = E_{i,i-1} acting on
basis vectors indexed 0..n.  Every fundamental representation is an exterior
power L(omega_k) = Lambda^k(C^{n+1}), on which the generators act by
derivations.  For a general dominant weight lambda = sum a_i omega_i we
realise L(lambda) as the submodule of

        tensor_i  Lambda^i(C^{n+1})^{tensor a_i}

generated by the tensor product of the highest weight vectors -- the Cartan
component -- by repeatedly applying lowering operators.  For a product of
factors we tensor the constructions.

The output is the same interface nullcone.py expects: a weight basis and
matrices for the raising operators.
"""
import itertools
from collections import defaultdict

P = 1000003


def rref(rows, ncols):
    mat = [r[:] for r in rows]
    piv, r = [], 0
    for c in range(ncols):
        p = next((i for i in range(r, len(mat)) if mat[i][c] % P), None)
        if p is None:
            continue
        mat[r], mat[p] = mat[p], mat[r]
        inv = pow(mat[r][c], P - 2, P)
        mat[r] = [(x * inv) % P for x in mat[r]]
        for i in range(len(mat)):
            if i != r and mat[i][c] % P:
                f = mat[i][c]
                mat[i] = [(mat[i][j] - f * mat[r][j]) % P for j in range(ncols)]
        piv.append(c)
        r += 1
        if r == len(mat):
            break
    return mat[:r], piv


# ------------------------------------------------------- one type-A factor
class TypeA:
    """sl_{n+1}, standard representation on basis 0..n."""

    def __init__(self, n):
        self.n = n
        self.N = n + 1

    def wt_std(self, j):
        """omega-coordinates of the weight of the j-th standard basis vector."""
        return tuple((1 if j == i - 1 else 0) - (1 if j == i else 0)
                     for i in range(1, self.n + 1))

    def wedge_basis(self, k):
        return list(itertools.combinations(range(self.N), k))

    def wedge_weight(self, k, b):
        w = [0] * self.n
        for j in b:
            wj = self.wt_std(j)
            for t in range(self.n):
                w[t] += wj[t]
        return tuple(w)

    def wedge_raise(self, k, i, b):
        """e_i on a wedge basis element: {basis: coeff}, e_i sends j=i to j=i-1."""
        out = {}
        for pos, j in enumerate(b):
            if j != i:
                continue
            if (i - 1) in b:
                continue
            nb = list(b)
            nb[pos] = i - 1
            sign = 1
            srt = sorted(nb)
            # sign of the permutation sorting nb
            perm = sorted(range(len(nb)), key=lambda t: nb[t])
            inv = sum(1 for a in range(len(perm)) for c in range(a + 1, len(perm))
                      if perm[a] > perm[c])
            sign = -1 if inv % 2 else 1
            out[tuple(srt)] = out.get(tuple(srt), 0) + sign
        return {k2: v % P for k2, v in out.items() if v % P}

    def wedge_lower(self, k, i, b):
        """f_i on a wedge basis element: sends j=i-1 to j=i."""
        out = {}
        for pos, j in enumerate(b):
            if j != i - 1:
                continue
            if i in b:
                continue
            nb = list(b)
            nb[pos] = i
            srt = sorted(nb)
            perm = sorted(range(len(nb)), key=lambda t: nb[t])
            inv = sum(1 for a in range(len(perm)) for c in range(a + 1, len(perm))
                      if perm[a] > perm[c])
            sign = -1 if inv % 2 else 1
            out[tuple(srt)] = out.get(tuple(srt), 0) + sign
        return {k2: v % P for k2, v in out.items() if v % P}


# ------------------------------------------ tensor products across factors
class Ambient:
    """tensor of wedge powers, one list per simple factor."""

    def __init__(self, factors, plan):
        """factors: list of TypeA.  plan: list over factors of a list of
        wedge degrees, e.g. plan[f] = [1,1,2] means Lambda^1 (x) Lambda^1 (x)
        Lambda^2 for factor f."""
        self.factors = factors
        self.plan = plan
        pieces = []
        for f, ks in enumerate(plan):
            for k in ks:
                pieces.append((f, k))
        self.pieces = pieces
        self.basis = list(itertools.product(
            *[factors[f].wedge_basis(k) for f, k in pieces]))
        self.index = {b: i for i, b in enumerate(self.basis)}

    def weight(self, b):
        w = []
        for f, fac in enumerate(self.factors):
            wf = [0] * fac.n
            for p, (ff, k) in enumerate(self.pieces):
                if ff != f:
                    continue
                wp = fac.wedge_weight(k, b[p])
                for t in range(fac.n):
                    wf[t] += wp[t]
            w += wf
        return tuple(w)

    def offset(self, f):
        return sum(self.factors[g].n for g in range(f))

    def act(self, vec, f, i, raising=True):
        """vec: {basis index: coeff}; apply e_i or f_i of factor f."""
        out = defaultdict(int)
        fac = self.factors[f]
        for bi, c in vec.items():
            b = self.basis[bi]
            for p, (ff, k) in enumerate(self.pieces):
                if ff != f:
                    continue
                sub = (fac.wedge_raise(k, i, b[p]) if raising
                       else fac.wedge_lower(k, i, b[p]))
                for nb, cc in sub.items():
                    nbl = list(b)
                    nbl[p] = nb
                    out[self.index[tuple(nbl)]] = (
                        out[self.index[tuple(nbl)]] + c * cc) % P
        return {k2: v % P for k2, v in out.items() if v % P}


def cartan_component(amb):
    """The submodule generated by the tensor of highest weight vectors."""
    hw = []
    for f, k in amb.pieces:
        hw.append(tuple(range(k)))            # e_0 ^ ... ^ e_{k-1}
    v0 = {amb.index[tuple(hw)]: 1}
    span = [v0]
    frontier = [v0]
    dim = len(amb.basis)

    def rowof(v):
        r = [0] * dim
        for k2, c in v.items():
            r[k2] = c % P
        return r

    R, piv = rref([rowof(v0)], dim)
    while frontier:
        nxt = []
        for v in frontier:
            for f, fac in enumerate(amb.factors):
                for i in range(1, fac.n + 1):
                    w = amb.act(v, f, i, raising=False)
                    if not w:
                        continue
                    cand = rowof(w)
                    R2, piv2 = rref(R + [cand], dim)
                    if len(R2) > len(R):
                        R, piv = R2, piv2
                        span.append(w)
                        nxt.append(w)
        frontier = nxt
    return span, R


class GenRep:
    """V = sum of irreducibles for a product of type-A factors.

    summands: list of highest weights, each a tuple of length sum(n_f),
    concatenating the omega-coordinates factor by factor."""

    def __init__(self, ranks, summands):
        self.factors = [TypeA(n) for n in ranks]
        self.ranks = list(ranks)
        self.k = sum(ranks)
        self.summands = [tuple(int(x) for x in s) for s in summands]
        self.basis = []           # (summand index, vector index within it)
        self.blocks = []
        for j, lam in enumerate(self.summands):
            plan = []
            off = 0
            for f, n in enumerate(ranks):
                ks = []
                for i in range(1, n + 1):
                    ks += [i] * lam[off + i - 1]
                plan.append(ks)
                off += n
            amb = Ambient(self.factors, plan)
            span, R = cartan_component(amb)
            self.blocks.append((amb, R))
            for t in range(len(R)):
                self.basis.append((j, t))
        self.index = {b: i for i, b in enumerate(self.basis)}
        self.dim = len(self.basis)

    def weight(self, b):
        j, t = b
        amb, R = self.blocks[j]
        row = R[t]
        piv = next(c for c in range(len(row)) if row[c] % P)
        return amb.weight(amb.basis[piv])

    def raise_matrix(self, idx):
        """Matrix of the idx-th raising operator (global index over factors)."""
        f, i = self._global(idx)
        M = defaultdict(dict)
        for c, b in enumerate(self.basis):
            j, t = b
            amb, R = self.blocks[j]
            vec = {k2: v for k2, v in enumerate(R[t]) if v % P}
            w = amb.act(vec, f, i, raising=True)
            if not w:
                continue
            row = [0] * len(amb.basis)
            for k2, v in w.items():
                row[k2] = v % P
            coords = self._coords(R, row)
            for t2, cc in enumerate(coords):
                if cc % P:
                    tgt = self.index[(j, t2)]
                    M[tgt][c] = cc % P
        return M

    def _global(self, idx):
        off = 0
        for f, n in enumerate(self.ranks):
            if idx < off + n:
                return f, idx - off + 1
            off += n
        raise IndexError

    @staticmethod
    def _coords(R, row):
        """Express row in terms of the rref basis R (assumed to span it)."""
        rem = row[:]
        out = [0] * len(R)
        for t, r in enumerate(R):
            piv = next((c for c in range(len(r)) if r[c] % P), None)
            if piv is None:
                continue
            if rem[piv] % P:
                co = rem[piv] % P
                out[t] = co
                rem = [(rem[c] - co * r[c]) % P for c in range(len(rem))]
        assert all(x % P == 0 for x in rem), "vector left the submodule"
        return out
